/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinni - vinni_@yahoo.com
 */
public class VentanaInicial extends javax.swing.JFrame {

    private DefaultTableModel modelTabla;

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        this.setTitle("ventana de Cargue");
        String[] columnas = {"Nombre ", "Apellido", "deporte", "edad", "Activo"};
        Object[][] datos = {{"Julian ", "Karlone", "baseball", new Integer(8), new Boolean(true)},
        {"Lucas", "Pusineri", "Futbol", new Integer(19), new Boolean(true)},
        {"Karen", "Macdonal", "Escalar", new Integer(22), new Boolean(false)},
        {"Angela", "Laulets", "Nada", new Integer(34), new Boolean(true)}};
//        Object [][] datos = {"Pepe", "Grillo", "Tenis", new Integer(5), new Boolean(false), "Pera"};

        modelTabla = new DefaultTableModel(datos, columnas);
        this.tabladato.setModel(modelTabla);
        tabladato.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 2) {
                    System.out.println("" + tabladato.getValueAt(tabladato.getSelectedRow(), 1));
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVerifica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladato = new javax.swing.JTable();
        mostrarVal = new javax.swing.JButton();
        btSeleccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Ventana"); // NOI18N
        getContentPane().setLayout(null);

        btVerifica.setText("Crear Tabla");
        btVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificaActionPerformed(evt);
            }
        });
        getContentPane().add(btVerifica);
        btVerifica.setBounds(30, 20, 160, 26);

        jScrollPane1.setViewportView(tabladato);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 100, 375, 130);

        mostrarVal.setText("Muestra valores");
        mostrarVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarValActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarVal);
        mostrarVal.setBounds(250, 20, 280, 26);

        btSeleccion.setText("Seleccionado");
        btSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionActionPerformed(evt);
            }
        });
        getContentPane().add(btSeleccion);
        btSeleccion.setBounds(290, 70, 150, 26);

        setSize(new java.awt.Dimension(570, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificaActionPerformed
        // TODO add your handling code here:
        crearTabla();
    }//GEN-LAST:event_btVerificaActionPerformed

    private void mostrarValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarValActionPerformed
        // TODO add your handling code here:
        mostrar();
    }//GEN-LAST:event_mostrarValActionPerformed

    private void btSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeleccionActionPerformed
        // TODO add your handling code here:
        seleccionar();
    }//GEN-LAST:event_btSeleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            //</editor-fold>
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSeleccion;
    private javax.swing.JButton btVerifica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarVal;
    private javax.swing.JTable tabladato;
    // End of variables declaration//GEN-END:variables

    private void crearTabla() {
        modelTabla.addColumn("Nombre");
        modelTabla.addColumn("Apellido");

        this.tabladato.setModel(modelTabla);

    }

    private void mostrar() {
        Object[] datos = new Object[2];
        datos[0] = "Julian";
        datos[1] = new Boolean(false);
        this.modelTabla.addRow(datos);
    }

    
    private void seleccionar() {
        int filaseleccionada = this.tabladato.getSelectedRow();
        if (filaseleccionada <0)
        {
            JOptionPane.showMessageDialog(this, "No selecciono fila", "Atencion", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        //JOptionPane.showMessageDialog(this, "Seleccion fila "+(filaseleccionada+1), "Atencion", JOptionPane.INFORMATION_MESSAGE);
         String dat1 = (String)tabladato.getValueAt(filaseleccionada, 0);
         String dat2 = (String)tabladato.getValueAt(filaseleccionada, 1);
         String dat3 = (String)tabladato.getValueAt(filaseleccionada, 2);
        Integer dat4 = (Integer)tabladato.getValueAt(filaseleccionada, 3);
        Boolean dat5 = (Boolean)tabladato.getValueAt(filaseleccionada, 4);
        JOptionPane.showMessageDialog(this, "Seleccion fila "+(filaseleccionada+1)+" -  "+
                dat1+" - "+dat2+" - "+dat3+" - "+dat4+" - "+dat5, " Atencion", JOptionPane.INFORMATION_MESSAGE);
        
        
    }
}
