/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Vinni - vinni_@yahoo.com
 */
public class VentanaGrafo extends javax.swing.JFrame {

    private javax.swing.JFileChooser jFSeleccion;

    /**
     * Creates new form VentanaInicial
     */
    public VentanaGrafo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVerifica = new javax.swing.JButton();
        cjCajaArchivo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cjDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cjMostrar = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Ventana"); // NOI18N
        getContentPane().setLayout(null);

        btVerifica.setText("Seleccionar Archivo");
        btVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificaActionPerformed(evt);
            }
        });
        getContentPane().add(btVerifica);
        btVerifica.setBounds(30, 20, 160, 26);
        getContentPane().add(cjCajaArchivo);
        cjCajaArchivo.setBounds(160, 150, 280, 20);

        jButton1.setText("Copiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 150, 81, 26);

        cjDestino.setText("C:\\apl\\basura\\");
            getContentPane().add(cjDestino);
            cjDestino.setBounds(160, 180, 150, 20);

            jLabel1.setText("Origen : ");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(70, 150, 60, 16);

            jLabel2.setText("destino: ");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(70, 180, 70, 16);

            cjMostrar.setText("Mostrar");
            cjMostrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cjMostrarActionPerformed(evt);
                }
            });
            getContentPane().add(cjMostrar);
            cjMostrar.setBounds(50, 260, 79, 26);

            lblFoto.setText("--");
            getContentPane().add(lblFoto);
            lblFoto.setBounds(230, 260, 180, 120);

            setSize(new java.awt.Dimension(802, 451));
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void btVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificaActionPerformed
        // TODO add your handling code here:
        seleccionar();


    }//GEN-LAST:event_btVerificaActionPerformed

    private void cjMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjMostrarActionPerformed
        // TODO add your handling code here:
        mostrar();
    }//GEN-LAST:event_cjMostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        copiar();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            //</editor-fold>
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaGrafo.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGrafo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerifica;
    private javax.swing.JTextField cjCajaArchivo;
    private javax.swing.JTextField cjDestino;
    private javax.swing.JButton cjMostrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables

    private File sf ; 
    private void seleccionar() {
        //FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes ",ImageIO.getReaderFileSuffixes());
        FileFilter imageFilter = new FileNameExtensionFilter("jpg, png, tiff, *", ImageIO.getReaderFileSuffixes());

        jFSeleccion = new JFileChooser();

        jFSeleccion.setFileFilter(imageFilter);
        int seleccion = jFSeleccion.showOpenDialog(this);
        

        sf = jFSeleccion.getSelectedFile();
        if (sf != null){
            this.cjCajaArchivo.setText(sf.getAbsolutePath());
            JOptionPane.showMessageDialog(this, "Archivo "+sf , "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
        

    }

    private void mostrar() {
        
        
    if (sf == null){
        JOptionPane.showMessageDialog(this, "No hay Imagen" , "Atencion", JOptionPane.ERROR_MESSAGE);
        return ;
    }
        
    File fCopia = new File(cjDestino.getText(), sf.getName());
    if (!fCopia.exists()){
        JOptionPane.showMessageDialog(this, "No existe el archivo, intente copiarlo de nuevo." , "Atencion", JOptionPane.ERROR_MESSAGE);
        return ;
    }
        try {
        

            ImageIcon icon = new ImageIcon(sf.toString());
            Icon  icono = new ImageIcon( icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
           
            lblFoto.setText(null);

            lblFoto.setIcon(icono);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null,
                    "Error abriendo la imagen " + ex);

        }
    }

    private void copiar() {
        if (sf == null && cjDestino.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "No selecciono archivo o la ruta esta vacia" , "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
        File fdestino = new File(cjDestino.getText());
        try {
            // copiar
            FileUtils.copyFileToDirectory(sf, fdestino);
            JOptionPane.showMessageDialog(this, "Archivo copiado en "+fdestino.getPath() , "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(VentanaGrafo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
